var maindata=[
    {"id":"button-baidu",//百度
        "icon":"icon-baidu",
        "url0":"https://www.baidu.com/",
        "url1":"https://www.baidu.com/s?wd="},
    {"id":"button-google",//谷歌
        "icon":"icon-google",
        "url0":"https://www.google.com",
        "url1":"https://www.google.com.hk/search?q="},
    {"id":"button-bing",//必应
        "icon":"icon-bing",
        "url0":"https://cn.bing.com",
        "url1":"https://cn.bing.com/search?q="},
    // {"id":"button-weixin",//微信
    //     "icon":"icon-weixin",
    //     "url0":"http://weixin.sogou.com",
    //     "url1":"http://weixin.sogou.com/weixin?type=2&query="},
    {"id":"button-weixin",//谷歌学术
        "icon":"icon-scholar",
        "url0":"https://www.labxing.com/paper",
        "url1":"https://scholar.google.com/scholar?q="},
    {"id":"button-wikipedia",//维基百科
        "icon":"icon-wikipedia",
        "url0":"https://en.wikipedia.org/wiki/Main_Page",
        "url1":"https://en.wikipedia.org/wiki/"},
    {"id":"button-bilibili",//哔哩哔哩
        "icon":"icon-bilibili",
        "url0":"https://t.bilibili.com/",
        "url1":"http://search.bilibili.com/all?keyword="},
    {"id":"button-zhihu",//知乎
        "icon":"icon-zhihu",
        "url0":"https://www.zhihu.com/",
        "url1":"https://www.zhihu.com/search?type=content&q="},
    {"id":"button-weibo",//微博
        "icon":"icon-weibo",
        "url0":"http://weibo.com",
        "url1":"http://s.weibo.com/weibo/"},
    {"id":"button-tieba",//贴吧
        "icon":"icon-tieba",
        "url0":"https://tieba.baidu.com/index.html",
        "url1":"http://tieba.baidu.com/f/search/res?ie=utf-8&qw="},
    {"id":"button-douban",//豆瓣
        "icon":"icon-douzi",
        "url0":"https://www.douban.com/",
        "url1":"https://www.douban.com/search?cat=1002&q="},
    
    {"id":"button-tencenttv",//腾讯视频
        "icon":"icon-tencenttv",
        "url0":"https://v.qq.com/",
        "url1":"https://v.qq.com/x/search/?q="},
    {"id":"button-youku",//胖鸟
        "icon":"icon-niao",
        "url0":"http://www.pniao.com/",
        "url1":"http://www.pniao.com/Mov/so/"},
    {"id":"button-baiduyun",//百度云
        "icon":"icon-baiduyun",
        "url0":"http://pan.baidu.com/disk/home",
        "url1":"http://www.xilinjie.com/s?q="},
    {"id":"button-youtube",//YouTube
        "icon":"icon-youtube1",
        "url0":"https://www.youtube.com/feed/subscriptions",
        "url1":"https://www.youtube.com/results?search_query="},
    {"id":"button-ustctv",//中科大网络电视
        "icon":"icon-tv",
        "url0":"http://tv.byr.cn/show",},
    {"id":"button-github",//GitHub
        "icon":"icon-github1",
        "url0":"https://github.com/",
        "url1":"https://github.com/search?utf8=✓&q="},
    {"id":"button-byrbt",//北邮人
        "icon":"icon-byrbt",
        "url0":"http://bt.byr.cn/index.php",
        "url1":"http://bt.byr.cn/torrents.php?search=",},
    {"id":"button-whubt",//珞樱
        "icon":"icon-whubt",
        "url0":"https://whu.pt/index.php",
        "url1":"https://whu.pt/torrents.php?search="},
    
  ]